INSERT INTO country (id,code,name) VALUES
                                       (1,'HU','Hungary'),
                                       (3,'AF','Afghanistan'),
                                       (5,'AX','Åland Islands'),
                                       (7,'AL','Albania'),
                                       (9,'DZ','Algeria'),
                                       (11,'AS','American Samoa'),
                                       (13,'AD','Andorra'),
                                       (15,'AO','Angola'),
                                       (17,'AI','Anguilla'),
                                       (19,'AQ','Antarctica');
INSERT INTO country (id,code,name) VALUES
                                       (21,'AG','Antigua and Barbuda'),
                                       (23,'AR','Argentina'),
                                       (25,'AM','Armenia'),
                                       (27,'AW','Aruba'),
                                       (29,'AU','Australia'),
                                       (31,'AT','Austria'),
                                       (33,'AZ','Azerbaijan'),
                                       (35,'BS','Bahamas'),
                                       (37,'BH','Bahrain'),
                                       (39,'BD','Bangladesh');
INSERT INTO country (id,code,name) VALUES
                                       (41,'BB','Barbados'),
                                       (43,'BY','Belarus'),
                                       (45,'BE','Belgium'),
                                       (47,'BZ','Belize'),
                                       (49,'BJ','Benin'),
                                       (51,'BM','Bermuda'),
                                       (53,'BT','Bhutan'),
                                       (55,'BO','Bolivia'),
                                       (57,'BQ','Bonaire'),
                                       (59,'BA','Bosnia and Herzegovina');
INSERT INTO country (id,code,name) VALUES
                                       (61,'BW','Botswana'),
                                       (63,'BV','Bouvet Island'),
                                       (65,'BR','Brazil'),
                                       (67,'IO','British Indian Ocean Territory'),
                                       (69,'BN','Brunei Darussalam'),
                                       (71,'BG','Bulgaria'),
                                       (73,'BF','Burkina Faso'),
                                       (75,'BI','Burundi'),
                                       (77,'KH','Cambodia'),
                                       (79,'CM','Cameroon');
INSERT INTO country (id,code,name) VALUES
                                       (81,'CA','Canada'),
                                       (83,'CV','Cape Verde'),
                                       (85,'KY','Cayman Islands'),
                                       (87,'CF','Central African Republic'),
                                       (89,'TD','Chad'),
                                       (91,'CL','Chile'),
                                       (93,'CN','China'),
                                       (95,'CX','Christmas Island'),
                                       (97,'CC','Cocos (Keeling) Islands'),
                                       (99,'CO','Colombia');
INSERT INTO country (id,code,name) VALUES
                                       (101,'KM','Comoros'),
                                       (103,'CG','Congo'),
                                       (105,'CD','Congo, the Democratic Republic of'),
                                       (107,'CK','Cook Islands'),
                                       (109,'CR','Costa Rica'),
                                       (111,'CI','Côte d''Ivoire'),
                                       (113,'HR','Croatia'),
                                       (115,'CU','Cuba'),
                                       (117,'CW','Curaçao'),
                                       (119,'CY','Cyprus');
INSERT INTO country (id,code,name) VALUES
                                       (121,'CZ','Czech Republic'),
                                       (123,'DK','Denmark'),
                                       (125,'DJ','Djibouti'),
                                       (127,'DM','Dominica'),
                                       (129,'DO','Dominican Republic'),
                                       (131,'EC','Ecuador'),
                                       (133,'EG','Egypt'),
                                       (135,'SV','El Salvador'),
                                       (137,'GQ','Equatorial Guinea'),
                                       (139,'ER','Eritrea');
INSERT INTO country (id,code,name) VALUES
                                       (141,'EE','Estonia'),
                                       (143,'ET','Ethiopia'),
                                       (145,'FK','Falkland Islands (Malvinas)'),
                                       (147,'FO','Faroe Islands'),
                                       (149,'FJ','Fiji'),
                                       (151,'FI','Finland'),
                                       (153,'FR','France'),
                                       (155,'GF','French Guiana'),
                                       (157,'PF','French Polynesia'),
                                       (159,'TF','French Southern Territories');
INSERT INTO country (id,code,name) VALUES
                                       (161,'GA','Gabon'),
                                       (163,'GM','Gambia'),
                                       (165,'GE','Georgia'),
                                       (167,'DE','Germany'),
                                       (169,'GH','Ghana'),
                                       (171,'GI','Gibraltar'),
                                       (173,'GR','Greece'),
                                       (175,'GL','Greenland'),
                                       (177,'GD','Grenada'),
                                       (179,'GP','Guadeloupe');
INSERT INTO country (id,code,name) VALUES
                                       (181,'GU','Guam'),
                                       (183,'GT','Guatemala'),
                                       (185,'GG','Guernsey'),
                                       (187,'GN','Guinea'),
                                       (189,'GW','Guinea-Bissau'),
                                       (191,'GY','Guyana'),
                                       (193,'HT','Haiti'),
                                       (195,'HM','Heard Island and McDonald Islands'),
                                       (197,'VA','Holy See (Vatican City State)'),
                                       (199,'HN','Honduras');
INSERT INTO country (id,code,name) VALUES
                                       (201,'HK','Hong Kong'),
                                       (203,'IS','Iceland'),
                                       (205,'IN','India'),
                                       (207,'ID','Indonesia'),
                                       (209,'IR','Iran, Islamic Republic of'),
                                       (211,'IQ','Iraq'),
                                       (213,'IE','Ireland'),
                                       (215,'IM','Isle of Man'),
                                       (217,'IL','Israel'),
                                       (219,'IT','Italy');
INSERT INTO country (id,code,name) VALUES
                                       (221,'JM','Jamaica'),
                                       (223,'JP','Japan'),
                                       (225,'JE','Jersey'),
                                       (227,'JO','Jordan'),
                                       (229,'KZ','Kazakhstan'),
                                       (231,'KE','Kenya'),
                                       (233,'KI','Kiribati'),
                                       (235,'KP','Korea, Democratic People''s Republic of'),
                                       (237,'KR','Korea, Republic of'),
                                       (239,'KW','Kuwait');
INSERT INTO country (id,code,name) VALUES
                                       (241,'KG','Kyrgyzstan'),
                                       (243,'LA','Lao People''s Democratic Republic'),
                                       (245,'LV','Latvia'),
                                       (247,'LB','Lebanon'),
                                       (249,'LS','Lesotho'),
                                       (251,'LR','Liberia'),
                                       (253,'LY','Libya'),
                                       (255,'LI','Liechtenstein'),
                                       (257,'LT','Lithuania'),
                                       (259,'LU','Luxembourg');
INSERT INTO country (id,code,name) VALUES
                                       (261,'MO','Macao'),
                                       (263,'MK','Macedonia'),
                                       (265,'MG','Madagascar'),
                                       (267,'MW','Malawi'),
                                       (269,'MY','Malaysia'),
                                       (271,'MV','Maldives'),
                                       (273,'ML','Mali'),
                                       (275,'MT','Malta'),
                                       (277,'MH','Marshall Islands'),
                                       (279,'MQ','Martinique');
INSERT INTO country (id,code,name) VALUES
                                       (281,'MR','Mauritania'),
                                       (283,'MU','Mauritius'),
                                       (285,'YT','Mayotte'),
                                       (287,'MX','Mexico'),
                                       (289,'FM','Micronesia, Federated States of'),
                                       (291,'MD','Moldova, Republic of'),
                                       (293,'MC','Monaco'),
                                       (295,'MN','Mongolia'),
                                       (297,'ME','Montenegro'),
                                       (299,'MS','Montserrat');
INSERT INTO country (id,code,name) VALUES
                                       (301,'MA','Morocco'),
                                       (303,'MZ','Mozambique'),
                                       (305,'MM','Myanmar'),
                                       (307,'NA','Namibia'),
                                       (309,'NR','Nauru'),
                                       (311,'NP','Nepal'),
                                       (313,'NL','Netherlands'),
                                       (315,'NC','New Caledonia'),
                                       (317,'NZ','New Zealand'),
                                       (319,'NI','Nicaragua');
INSERT INTO country (id,code,name) VALUES
                                       (321,'NE','Niger'),
                                       (323,'NG','Nigeria'),
                                       (325,'NU','Niue'),
                                       (327,'NF','Norfolk Island'),
                                       (329,'MP','Northern Mariana Islands'),
                                       (331,'NO','Norway'),
                                       (333,'OM','Oman'),
                                       (335,'PK','Pakistan'),
                                       (337,'PW','Palau'),
                                       (339,'PS','Palestine, State of');
INSERT INTO country (id,code,name) VALUES
                                       (341,'PA','Panama'),
                                       (343,'PG','Papua New Guinea'),
                                       (345,'PY','Paraguay'),
                                       (347,'PE','Peru'),
                                       (349,'PH','Philippines'),
                                       (351,'PN','Pitcairn'),
                                       (353,'PL','Poland'),
                                       (355,'PT','Portugal'),
                                       (357,'PR','Puerto Rico'),
                                       (359,'QA','Qatar');
INSERT INTO country (id,code,name) VALUES
                                       (361,'RE','Réunion'),
                                       (363,'RO','Romania'),
                                       (365,'RU','Russian Federation'),
                                       (367,'RW','Rwanda'),
                                       (369,'BL','Saint Barthélemy'),
                                       (371,'SH','Saint Helena, Ascension and Tristan da Cunha'),
                                       (373,'KN','Saint Kitts and Nevis'),
                                       (375,'LC','Saint Lucia'),
                                       (377,'MF','Saint Martin (French part)'),
                                       (379,'PM','Saint Pierre and Miquelon');
INSERT INTO country (id,code,name) VALUES
                                       (381,'VC','Saint Vincent and the Grenadines'),
                                       (383,'WS','Samoa'),
                                       (385,'SM','San Marino'),
                                       (387,'ST','Sao Tome and Principe'),
                                       (389,'SA','Saudi Arabia'),
                                       (391,'SN','Senegal'),
                                       (393,'RS','Serbia'),
                                       (395,'SC','Seychelles'),
                                       (397,'SL','Sierra Leone'),
                                       (399,'SG','Singapore');
INSERT INTO country (id,code,name) VALUES
                                       (401,'SX','Sint Maarten (Dutch part)'),
                                       (403,'SK','Slovakia'),
                                       (405,'SI','Slovenia'),
                                       (407,'SB','Solomon Islands'),
                                       (409,'SO','Somalia'),
                                       (411,'ZA','South Africa'),
                                       (413,'GS','South Georgia and the South Sandwich Islands'),
                                       (415,'SS','South Sudan'),
                                       (417,'ES','Spain'),
                                       (419,'LK','Sri Lanka');
INSERT INTO country (id,code,name) VALUES
                                       (421,'SD','Sudan'),
                                       (423,'SR','Suriname'),
                                       (425,'SJ','Svalbard and Jan Mayen'),
                                       (427,'SZ','Swaziland'),
                                       (429,'SE','Sweden'),
                                       (431,'CH','Switzerland'),
                                       (433,'SY','Syrian Arab Republic'),
                                       (435,'TW','Taiwan'),
                                       (437,'TJ','Tajikistan'),
                                       (439,'TZ','Tanzania, United Republic of');
INSERT INTO country (id,code,name) VALUES
                                       (441,'TH','Thailand'),
                                       (443,'TL','Timor-Leste'),
                                       (445,'TG','Togo'),
                                       (447,'TK','Tokelau'),
                                       (449,'TO','Tonga'),
                                       (451,'TT','Trinidad and Tobago'),
                                       (453,'TN','Tunisia'),
                                       (455,'TR','Turkey'),
                                       (457,'TM','Turkmenistan'),
                                       (459,'TC','Turks and Caicos Islands');
INSERT INTO country (id,code,name) VALUES
                                       (461,'TV','Tuvalu'),
                                       (463,'UG','Uganda'),
                                       (465,'UA','Ukraine'),
                                       (467,'AE','United Arab Emirates'),
                                       (469,'GB','United Kingdom'),
                                       (471,'US','United States'),
                                       (473,'UM','United States Minor Outlying Islands'),
                                       (475,'UY','Uruguay'),
                                       (477,'UZ','Uzbekistan'),
                                       (479,'VU','Vanuatu');
INSERT INTO country (id,code,name) VALUES
                                       (481,'VE','Venezuela'),
                                       (483,'VN','Viet Nam'),
                                       (485,'VG','Virgin Islands, British'),
                                       (487,'VI','Virgin Islands, U.S.'),
                                       (489,'WF','Wallis and Futuna'),
                                       (491,'EH','Western Sahara'),
                                       (493,'YE','Yemen'),
                                       (495,'ZM','Zambia'),
                                       (497,'ZW','Zimbabwe');
