INSERT INTO room (id,room_type,bed,quantity,price,currency_id,vat_info_id,congress_hotel_id,online_visibility,online_label,online_external_link,online_external_email) VALUES
                                                                                                                                                                           (1875,'Egyágyas szoba (ÁFA tv15.§)',1,108,69000.00,1,7,603,'NOT_VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (1878,'Kétágyas szoba (ÁFA tv15.§)',2,13,75000.00,1,7,603,'NOT_VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (1932,'VILLA 3 ágyas (ÁFA tv15.§)',3,2,120000.00,1,7,603,'NOT_VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (1935,'VILLA 4 ágyas (ÁFA tv15.§)',4,1,160000.00,1,7,603,'NOT_VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (1938,'VILLA 5 ágyas (ÁFA tv15.§)',5,2,195000.00,1,7,603,'NOT_VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (1941,'VILLA 2 ágyas (ÁFA tv15.§)',2,5,80000.00,1,7,603,'NOT_VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2028,'Kétágyas diff',2,5,6000.00,1,7,603,'NOT_VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2058,'Kutyafelár',2,10,14000.00,1,7,603,'NOT_VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2118,'Villa 1 ágyas (ÁFA tv15.§)',1,1,75000.00,1,7,603,'NOT_VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (1881,'Egyágyas szoba (ÁFA tv15.§)',1,105,59000.00,1,7,606,'NOT_VISIBLE',NULL,NULL,NULL);
INSERT INTO room (id,room_type,bed,quantity,price,currency_id,vat_info_id,congress_hotel_id,online_visibility,online_label,online_external_link,online_external_email) VALUES
                                                                                                                                                                           (1884,'Kétágyas szoba (ÁFA tv15.§)',2,3,69000.00,1,7,606,'NOT_VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (1887,'Egyágyas (ÁFA tv15.§)',1,82,55000.00,1,7,609,'NOT_VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (1890,'Kétágyas szoba (ÁFA tv15.§)',2,4,71000.00,1,7,609,'NOT_VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2112,'Egyágyas szoba',1,4,33000.00,1,7,648,'VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2115,'Kétágyas szoba',2,4,43000.00,1,7,648,'VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2175,'Egyágyas szoba (ÁFA tv15.§)',1,15,43000.00,1,7,666,'VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2178,'Kétágyas szoba (ÁFA tv15.§)',2,15,48000.00,1,7,666,'VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2181,'Egyágyas szoba (ÁFA tv15.§)',1,25,85000.00,1,7,669,'VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2184,'Kétágyas szoba (ÁFA tv15.§)',2,25,96000.00,1,7,669,'VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2223,'Egyágyas szoba (ÁFA tv15.§)',1,9,28000.00,1,7,672,'VISIBLE','(CSAK 05.29. estére elérhető)',NULL,NULL);
INSERT INTO room (id,room_type,bed,quantity,price,currency_id,vat_info_id,congress_hotel_id,online_visibility,online_label,online_external_link,online_external_email) VALUES
                                                                                                                                                                           (2226,'Kétágyas szoba (ÁFA tv15.§)',2,9,36000.00,1,7,672,'VISIBLE','(CSAK 05.29. estére elérhető)',NULL,NULL),
                                                                                                                                                                           (2229,'Egyágyas szoba (ÁFA tv15.§)',1,25,77000.00,1,7,675,'VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2232,'Kétágyas szoba (ÁFA tv15.§)',2,25,92000.00,1,7,675,'VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2253,'Egyágyas szoba (ÁFA tv15.§)',1,10,78000.00,1,7,678,'VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2256,'Kétágyas szoba (ÁFA tv15.§)',2,10,90000.00,1,7,678,'VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2199,'Nem panorámás 1ágyas(ÁFA tv15.§)',1,5,86000.00,1,7,684,'NOT_VISIBLE','(Nem panorámás)',NULL,NULL),
                                                                                                                                                                           (2202,'Nem panorámás 2ágyas(ÁFA tv15.§)',2,10,87000.00,1,7,684,'NOT_VISIBLE','(Nem panorámás)',NULL,NULL),
                                                                                                                                                                           (2205,'Panorámás egyágyas (ÁFA tv15.§)',1,5,93000.00,1,7,684,'NOT_VISIBLE','(Panorámás)',NULL,NULL),
                                                                                                                                                                           (2208,'Panorámás kétágyas (ÁFA tv15.§)',2,6,94000.00,1,7,684,'NOT_VISIBLE','(Panorámás)',NULL,NULL),
                                                                                                                                                                           (2211,'Classic lakosztály 1(ÁFA tv15.§)',1,2,95000.00,1,7,684,'NOT_VISIBLE','(Lakosztály-classic)',NULL,NULL);
INSERT INTO room (id,room_type,bed,quantity,price,currency_id,vat_info_id,congress_hotel_id,online_visibility,online_label,online_external_link,online_external_email) VALUES
                                                                                                                                                                           (2214,'Classic lakosztály 2(ÁFA tv15.§)',2,2,96000.00,1,7,684,'NOT_VISIBLE','(Lakosztály-classic)',NULL,NULL),
                                                                                                                                                                           (2217,'Panoráma lakosztály1(ÁFA tv15.§)',1,2,101000.00,1,7,684,'NOT_VISIBLE','(Lakosztály-panorámás)',NULL,NULL),
                                                                                                                                                                           (2220,'Panoráma lakosztály2(ÁFA tv15.§)',2,3,102000.00,1,7,684,'NOT_VISIBLE','(Lakosztály-panorámás)',NULL,NULL),
                                                                                                                                                                           (2193,'Egyágyas szoba (ÁFA tv15.§)',1,20,78000.00,1,7,687,'VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2196,'Kétágyas szoba (ÁFA tv15.§)',2,20,84000.00,1,7,687,'VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2187,'Egyágyas szoba (ÁFA tv15.§)',1,11,45000.00,1,7,690,'VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2190,'Kétágyas szoba (ÁFA tv15.§)',2,11,58000.00,1,7,690,'VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2286,'Egyágyas szoba (ÁFA tv15.§)',1,25,56000.00,1,7,693,'VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2289,'Kétágyas szoba (ÁFA tv15.§)',2,25,67000.00,1,7,693,'VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2274,'Egyágyas VEZ ( ÁFA tv15.§)',1,13,55000.00,1,7,696,'NOT_VISIBLE',NULL,NULL,NULL);
INSERT INTO room (id,room_type,bed,quantity,price,currency_id,vat_info_id,congress_hotel_id,online_visibility,online_label,online_external_link,online_external_email) VALUES
                                                                                                                                                                           (2277,'Kétágyas VEZ ( ÁFA tv15.§)',2,19,65000.00,1,7,696,'NOT_VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2325,'Egyágyas ( ÁFA tv15.§)',1,12,55000.00,1,7,696,'NOT_VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2328,'Kétágyas ( ÁFA tv15.§)',2,6,65000.00,1,7,696,'NOT_VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2259,'Egyágyas szoba+R (ÁFA tv15.§)',1,5,52000.00,1,7,699,'VISIBLE','(Szoba reggelivel)',NULL,NULL),
                                                                                                                                                                           (2262,'Kétágyas szoba+R (ÁFA tv15.§)',2,5,59000.00,1,7,699,'VISIBLE','(Szoba reggelivel)',NULL,NULL),
                                                                                                                                                                           (2265,'Egyágyas apartman+R (ÁFA tv15.§)',1,2,60000.00,1,7,699,'VISIBLE','(Apartman reggelivel)',NULL,NULL),
                                                                                                                                                                           (2268,'Kétágyas apartman+R (ÁFA tv15.§)',2,2,67000.00,1,7,699,'VISIBLE','(Apartman reggelivel)',NULL,NULL),
                                                                                                                                                                           (2292,'Egyágyas apartman (ÁFA tv15.§)',1,2,54000.00,1,7,699,'VISIBLE','(Apartman reggeli NÉLKÜL)',NULL,NULL),
                                                                                                                                                                           (2295,'Egyágyas szoba (ÁFA tv15.§)',1,5,46000.00,1,7,699,'VISIBLE','(Szoba reggeli NÉLKÜL)',NULL,NULL),
                                                                                                                                                                           (2298,'Kétágyas apartman (ÁFA tv15.§)',2,2,55000.00,1,7,699,'VISIBLE','(Apartman reggeli NÉLKÜL)',NULL,NULL);
INSERT INTO room (id,room_type,bed,quantity,price,currency_id,vat_info_id,congress_hotel_id,online_visibility,online_label,online_external_link,online_external_email) VALUES
                                                                                                                                                                           (2301,'Kétágyas szoba (ÁFA tv15.§)',2,5,47000.00,1,7,699,'VISIBLE','(Szoba reggeli NÉLKÜL)',NULL,NULL),
                                                                                                                                                                           (2304,'Lakosztály 2 szobás (ÁFA tv15.§)',2,1,83000.00,1,7,699,'VISIBLE','(Lakosztály max. 4 fő)',NULL,NULL),
                                                                                                                                                                           (2319,'Egyágyas szoba (ÁFA tv15.§)',1,10,42000.00,1,7,711,'VISIBLE',NULL,NULL,NULL),
                                                                                                                                                                           (2322,'Kétágyas szoba (ÁFA tv15.§)',2,10,55000.00,1,7,711,'VISIBLE',NULL,NULL,NULL);
